template_image = "./templates/template-2.png"
output_dir = "./output"
log_file = "./logs/frantic-postr.log"
label_config = "./labels.toml"

[plex]
base_url = "http://192.168.1.195:32400"
token = "yooyQkcTthoasndvsQnU"
retries = 3
workers = 5
retry_base_ms = 500
retry_max_ms = 30000



[clean.replacements]
"&" = " and "
"£" = " GBP "
"$" = " Dollar "
"FULL MOVIE" = " "

[clean]
translate_api_http_address = "https://libretranslate.com/translate"
translate_endpoint = "https://libretranslate.com/translate"
translate_api_key = ""
translate_rate_limit_per_minute = 10

[font]
file = "./fonts/Drips.ttf"
size = 140
color = "#FFFFFF"
shadow_color = "#7b8204"
shadow_offset_x = 2
shadow_offset_y = 2
glow_color = "#fbff00"
glow_radius = 2
glow_alpha = 0.9
y_offset = 0
