template_image = "./template.png"
output_dir = "./output"
log_file = "./frantic-postr.log"

[plex]
base_url = "http://127.0.0.1:32400"
token = "YOUR_PLEX_TOKEN"

[font]
file = ""
size = 64
color = "#FFFFFF"
shadow_color = "#000000"
shadow_offset_x = 2
shadow_offset_y = 2
glow_color = "#000000"
glow_radius = 3
glow_alpha = 0.35
y_offset = 0
